name: book-depository

services:
  api:
    image: node:16.13.0-alpine3.14
    ports:
      - 5001-5002:5001-5002
    user: node
    working_dir: /app
    command: ./docker.sh
    volumes:
      - .:/app
    links:
      - postgres

  postgres:
    image: postgres:16-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: